// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otqhldhixgsjbthujdxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cWhsZGhpeGdzamJ0aHVqZHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTI4MjMsImV4cCI6MjA3MzQ2ODgyM30.hBzcKQUhYW6SHqDHnKYliGb2YeCAYGYqT8t7lCTgZ0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});